name: Update README with latest examples

on:
    push:
        paths:
            - 'tests/csv/day_report/odoo_expected.txt'
            - 'tests/csv/day_report/redmine_expected.txt'
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Update README
                run: |
                    ODOO_EXAMPLE=$(cat tests/csv/day_report/odoo_expected.txt)
                    REDMINE_EXAMPLE=$(cat tests/csv/day_report/redmine_expected.txt)
                    
                    # Read the README file into a variable
                    README_CONTENT=$(cat README.md)
                    
                    # Replace the placeholders
                    README_CONTENT="${README_CONTENT//ODOO_EXAMPLE/$ODOO_EXAMPLE}"
                    README_CONTENT="${README_CONTENT//REDMINE_EXAMPLE/$REDMINE_EXAMPLE}"
                    
                    # Write the updated content back to README.md
                    echo "$README_CONTENT" > README.md


            -   name: Commit changes
                env:
                    GITHUB_TOKEN: ${{ secrets.PATCH_TOKEN }}
                run: |
                    git config --local user.name "github-actions"
                    git config --local user.email "github-actions@github.com"
                    git add README.md
                    git commit -m "Update README with latest examples" || echo "No changes to commit"
                    git push